# Generated by Django 4.1.13 on 2024-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
    ]
