# Generated by Django 4.1.13 on 2024-02-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
